### ISSUE TITLE
Some questions about the project

### ISSUE THREAD

**Issue by OwalnutO** [val-iisc/deligan#2]
Two questions:
1.Do you find performance reduction if you increase the size of the generated image? Such as the dataset of the sketch? Can you give some suggestions if I want to increase the size of the results?
2.How to modify the network if I want to generate specific kind of images, just like the conditional GAN? Any suggestions?
Thanks!

**Comment by swami1995** [comment]
We didn't really perform any experiments with increased image resolution. But my intuition says simply increasing the image size would result in performance deterioration. I think you'd have to correspondingly increase the dataset size. Also, I think it'll require some hyperparameter tuning. But I think you should observe better performance once you make these changes. 
In order to get conditional generation in a DeliGAN setting, just take any conditional GAN framework, and sample from the mixture of Gaussian setup as in DeliGAN, instead of using a unit normal distribution . This was the point of DeliGAN. View it more like a layer that can be plugged into any other architecture to learn a more flexible prior distribution for the generator. You could also tweak the DeliGAN model we have provided to emulate the conditional GAN setup, but that would be more cumbersome.
