### ISSUE TITLE
fixed batch size

### ISSUE THREAD

**Issue by SchafferZhang** [val-iisc/deligan#5]
if I want to apply deli-GAN's spirits to some other application like conditional GAN , so the batch size have to fixed? I think this is not convenient.

**Comment by swami1995** [comment]
Hi, thanks for your question.
I'm not sure I understand why it's problematic to apply deligan with fixed batch size in conditional GAN. Could you please elaborate upon what you mean and why fixed batch sizes would be inconvenient?

**Comment by SchafferZhang** [comment]
Thanks for your reply @swami1995 . I will make my question more specific. In the paper, you substitute the random noise z with a mixture of Gaussian distributions, and you set the number of the distribution to N, which is the batch size. So if I want to generate 2N samples at a time, it will not be convenient. What I mean is that in your implementation, the batch size have to be fixed during training phase, not like some other network, which the batch size can be set  to None.

**Comment by swami1995** [comment]
Hi,
I'm sorry, I think I didn't see your messages earlier.
Coming to the question. You are right, I agree that is an inconvenience. The problem was that if we don't specify that, we'd have to make the computational graph dynamic and tensorflow didn't support that. But now that we have various frameworks which support dynamic graphs, I think it shouldn't be a huge problem now.
